---
title: "git_01"
author: "Kaylie Fagoaga"
date: "summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

In woven tapestry of time and space,  
Our souls entwined, in this mortal race.   
Two hearts, two minds, in passion's embrace,  
Bound by fate, in love's relentless chase.  
  
Yet shadows linger, and darkness falls,  
As whispers haunt these hallowed halls.  
In every joy, a sorrow calls,  
A dance of life within death's thralls.  
  
For who can defy the hands of fate,  
Or challenge the decree of heaven's gate?  
In life's tempest, we navigate,  
Seeking solace, before it's too late.  
  
So let us seize this fleeting hour,  
Embrace the flame, defy the dour.  
For love, the eternal, has the power,  
To transcend all, in its sacred bower.  


